modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 2 (GPLv2)"

[[mods]]
modId="sufferance"
version="1.3.2"
displayName="Sufferance"
credits="NovaGalaxy for creating Sufferance, Arathain for creating Charter"
displayURL="https://github.com/Synxhronize/sufferance"
authors="NovaGalaxy"

[[dependencies.sufferance]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




